services:
- type: web
  name: sirohi-backend
  runtime: python
  repo: https://github.com/sirohi2535/Sirohi-backend
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  envVars:
  - key: PORT
    value: 10000
version: "1"
